//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tuple", Namespace="http://schemas.datacontract.org/2004/07/MathService")]
    public partial class Tuple : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double[] DataField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinearSystem", Namespace="http://schemas.datacontract.org/2004/07/MathService")]
    public partial class LinearSystem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double[][] CoefficientsField;
        
        private double[] ConstantsField;
        
        private double[][] _coefficientsField;
        
        private double[] _constantsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Coefficients
        {
            get
            {
                return this.CoefficientsField;
            }
            set
            {
                this.CoefficientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Constants
        {
            get
            {
                return this.ConstantsField;
            }
            set
            {
                this.ConstantsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] _coefficients
        {
            get
            {
                return this._coefficientsField;
            }
            set
            {
                this._coefficientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] _constants
        {
            get
            {
                return this._constantsField;
            }
            set
            {
                this._constantsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMath")]
public interface IMath
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Prime", ReplyAction="http://tempuri.org/IMath/PrimeResponse")]
    bool Prime(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Prime", ReplyAction="http://tempuri.org/IMath/PrimeResponse")]
    System.Threading.Tasks.Task<bool> PrimeAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/SumTuple", ReplyAction="http://tempuri.org/IMath/SumTupleResponse")]
    MathService.Tuple SumTuple(MathService.Tuple tuple);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/SumTuple", ReplyAction="http://tempuri.org/IMath/SumTupleResponse")]
    System.Threading.Tasks.Task<MathService.Tuple> SumTupleAsync(MathService.Tuple tuple);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/SolveLinearSystem", ReplyAction="http://tempuri.org/IMath/SolveLinearSystemResponse")]
    double[] SolveLinearSystem(MathService.LinearSystem system);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/SolveLinearSystem", ReplyAction="http://tempuri.org/IMath/SolveLinearSystemResponse")]
    System.Threading.Tasks.Task<double[]> SolveLinearSystemAsync(MathService.LinearSystem system);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMathChannel : IMath, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MathClient : System.ServiceModel.ClientBase<IMath>, IMath
{
    
    public MathClient()
    {
    }
    
    public MathClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MathClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool Prime(int value)
    {
        return base.Channel.Prime(value);
    }
    
    public System.Threading.Tasks.Task<bool> PrimeAsync(int value)
    {
        return base.Channel.PrimeAsync(value);
    }
    
    public MathService.Tuple SumTuple(MathService.Tuple tuple)
    {
        return base.Channel.SumTuple(tuple);
    }
    
    public System.Threading.Tasks.Task<MathService.Tuple> SumTupleAsync(MathService.Tuple tuple)
    {
        return base.Channel.SumTupleAsync(tuple);
    }
    
    public double[] SolveLinearSystem(MathService.LinearSystem system)
    {
        return base.Channel.SolveLinearSystem(system);
    }
    
    public System.Threading.Tasks.Task<double[]> SolveLinearSystemAsync(MathService.LinearSystem system)
    {
        return base.Channel.SolveLinearSystemAsync(system);
    }
}
